version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    pull-request-branch-name:
      separator: '-'
    ignore:
      # on higher version than current alpha version.
      - dependency-name: '@docsearch/*'
